language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install: 
  - pip install -e ".[test]"  --upgrade
# command to run tests
script:
  - aloe tests/ --verbose
